---
abstract: 'easily build tree structures'
author:
  - 'Gianni Ceccarelli <dakkar@thenautilus.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tree-Template-Declare
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Devel::Caller: 0
  Sub::Exporter: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.5
